### ISSUE TITLE
Python 3.7 wheels?

### ISSUE THREAD

**Issue by matthew-brett** [andfoy/pywinpty#116]
Any chance of providing wheels for Python 3.7?  Can I help?  I do a lot of package building...

**Comment by andfoy** [comment]
@matthew-brett Thanks for your iniciative, right now we're using conda-forge to build and upload our wheels. While in principle, we support 2.7, 3.5 and 3.7, you can build the 3.7 wheels until they are supported by conda. However, we don't guarantee that they will get updated when a new release should be available.

**Comment by matthew-brett** [comment]
Aha - I see you need the winpty package installed, and maybe you need the mingw-w64 compiler?

Does conda-forge not yet support Python 3.7?

**Comment by ccordoba12** [comment]
We use the Anaconda packages and toolchain to create our packages, so we have to wait until they provide the packages that we need to build our wheels.

**Comment by matthew-brett** [comment]
I'll try and work out how to build without conda, but I'm very busy these next few days, maybe Saturday.

**Comment by ccordoba12** [comment]
@matthew-brett, thanks for your offer but I don't think we'd accept such a contribution. We prefer to stick to conda packages because we know them very well, we have a close relationship with the Anaconda team and we already moved from one toolchain to another (VS to MSYS2) and it halted the project for a couple of months.

**Comment by matthew-brett** [comment]
Ah - no - I wasn't expecting you to merge what I did - I was only going to build a separate repo that can build wheels.  You can ignore it peacefully if it is of no use to you.

**Comment by ccordoba12** [comment]
> You can ignore it peacefully if it is of no use to you.

Ok, if you want to build your own wheels, then we don't have a problem with that.
