### ISSUE TITLE
Possibly of interest?

### ISSUE THREAD

**Issue by dhirschfeld** [andfoy/pywinpty#117]
In case you hadn't already seen:

https://blogs.msdn.microsoft.com/commandline/2018/08/02/windows-command-line-introducing-the-windows-pseudo-console-conpty/

Feel free to close as this isn't really an issue.

**Comment by andfoy** [comment]
@dhirschfeld, thanks for the update. It seems that it will take some time to have ConPTY available, also, it seems that it will be supported only by Windows 10, which leaves other mainstream versions such as 7 or 8 without native PTY support. We will have to wait until the official release.

**Comment by ccordoba12** [comment]
Cool stuff, thanks for sharing @dhirschfeld!

**Comment by dhirschfeld** [comment]
Yeah, it will be years before you can assume it's available (Win7 EOL is Jan 2020). Still, it's an interesting development!
