### ISSUE TITLE
Support ConPTY on Windows 10

### ISSUE THREAD

**Issue by andfoy** [andfoy/pywinpty#122]
https://devblogs.microsoft.com/commandline/windows-command-line-introducing-the-windows-pseudo-console-conpty/

**Comment by dhirschfeld** [comment]
***xref:*** #117

**Comment by ccordoba12** [comment]
Also https://github.com/Microsoft/node-pty/pull/236

**Comment by randy3k** [comment]
Wow, can't believe that it will happen this soon.
