### ISSUE TITLE
pip install fails on Python 3.8/Windoes

### ISSUE THREAD

**Issue by AndrewUshakov** [andfoy/pywinpty#123]
Please, add support to Python 3.8/Windows 64 bit. Situation is exactly the same as in issue #118.

**Comment by andfoy** [comment]
@AndrewUshakov, thanks for reporting this one, however, will be unable to fix it until conda publishes 3.8 packages officially. In the meantime, please try the building instructions at https://github.com/spyder-ide/pywinpty#building-from-source, this requires you to compile and install [winpty](https://github.com/rprichard/winpty) binaries and MSYS2/MinGW compilers.

**Comment by AndrewUshakov** [comment]
@andfoy,  thank you. I created this issue only because I discovered it during installation of jupyter package with pip. That is, problem can influence on many people. Also, working whl can be found here: https://www.lfd.uci.edu/~gohlke/pythonlibs/#pywinpty so I do not understand, why did you mention conda?

**Comment by andfoy** [comment]
Our build system depends on conda-forge, do we depend on it

**Comment by riyadfebrian** [comment]
i had the same problem on python 3.8.
 do u know when Anaconda for 3.8 packages will release ?

**Comment by mlabarrere** [comment]
Hello,

As seen on the https://anaconda.org/anaconda/python, Anaconda Python 3.8 is available.

Do you have an option to install `pywinpty` gracefully? The `jupyter notebook` install depends on it.

Many thanks for your help.

Best

**Comment by atakli** [comment]
@mlabarrere I had a problem with installing jupyter for python 3.8. Then I have installed pywinpty from [here ](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pywinpty)and solved.
