### ISSUE TITLE
argv[0] empty string in spawned executable

### ISSUE THREAD

**Issue by idorurez** [andfoy/pywinpty#124]
Not sure if this is a limitation of winpty/pywinpty, but when I spawn "program.exe" and loop through argv, argc does note the total arguments, but argv[0] remains an empty string--everything else appears just fine. This isn't an issue when I run the command in Windows Powershell however.

Any idea where I can start looking?

**Comment by idorurez** [comment]
To be precise, I have "program.exe" print out all of the arguments from 0 to argc-1 just to be sure I wasn't going crazy.

**Comment by goanpeca** [comment]
What do you think the problem is @andfoy ?

**Comment by shimondoodkin** [comment]
The first argument is skipped and i don't understand why
