### ISSUE TITLE
pip install fails on Python 3.8 32-bit, prevents Jupyter install 

### ISSUE THREAD

**Issue by kikumar3189** [andfoy/pywinpty#129]
pip install --proxy=<proxy> pywinpty

Collecting pywinpty
  Using cached https://files.pythonhosted.org/packages/5d/97/8e43c2152a638cdb83d45644eb125c752abe67249f94bb3e3e29b0709685/pywinpty-0.5.7.tar.gz
Building wheels for collected packages: pywinpty
  Building wheel for pywinpty (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\program files (x86)\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\a565350\\AppData\\Local\\Temp\\1\\pip-install-ccs8z3nl\\pywinpty\\setup.py'"'"'; __file__='"'"'C:\\Users\\a565350\\AppData\\Local\\Temp\\1\\pip-install-ccs8z3nl\\pywinpty\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\a565350\AppData\Local\Temp\1\pip-wheel-oarenqme' --python-tag cp38
       cwd: C:\Users\a565350\AppData\Local\Temp\1\pip-install-ccs8z3nl\pywinpty\
  Complete output (25 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.8
  creating build\lib.win32-3.8\winpty
  copying winpty\ptyprocess.py -> build\lib.win32-3.8\winpty
  copying winpty\winpty_wrapper.py -> build\lib.win32-3.8\winpty
  copying winpty\__init__.py -> build\lib.win32-3.8\winpty
  creating build\lib.win32-3.8\winpty\tests
  copying winpty\tests\test_cywinpty.py -> build\lib.win32-3.8\winpty\tests
  copying winpty\tests\test_ptyprocess.py -> build\lib.win32-3.8\winpty\tests
  copying winpty\tests\test_winpty_wrapper.py -> build\lib.win32-3.8\winpty\tests
  copying winpty\tests\__init__.py -> build\lib.win32-3.8\winpty\tests
  creating build\lib.win32-3.8\winpty\_winpty
  copying winpty\_winpty\__init__.py -> build\lib.win32-3.8\winpty\_winpty
  running build_ext
  building 'winpty.cywinpty' extension
  creating build\temp.win32-3.8
  creating build\temp.win32-3.8\Release
  creating build\temp.win32-3.8\Release\winpty
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD "-Ic:\program files (x86)\python38-32\include" "-Ic:\program files (x86)\python38-32\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" -IC:\SYBASE\OCS-12_5\include -IC:\SYBASE\OCS-15_0\include /Tcwinpty/cywinpty.c /Fobuild\temp.win32-3.8\Release\winpty/cywinpty.obj
  cywinpty.c
  winpty/cywinpty.c(629): fatal error C1083: Cannot open include file: 'winpty.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for pywinpty
  Running setup.py clean for pywinpty
Failed to build pywinpty

**Comment by ccordoba12** [comment]
We can't generate 32 bit wheels, sorry. Please use a 64bit build of Python.

**Comment by Elijah57** [comment]
> We can't generate 32 bit wheels, sorry. Please use a 64bit build of Python.

can I install 64bit build of python on a 32 bit machine(windows 7)

**Comment by ccordoba12** [comment]
No, you can't, sorry.
