### ISSUE TITLE
pip install fails on 3.8.1, prevents Jupyter install

### ISSUE THREAD

**Issue by Zikoat** [andfoy/pywinpty#130]
Facing the same issue for Python 3.8 32 Bit on Win 10

_Originally posted by @kikumar3189 in https://github.com/spyder-ide/pywinpty/issues/118#issuecomment-570467209_

**Comment by ccordoba12** [comment]
Sorry but we don't have the means to create 32 bit wheels. It's 2020, so it's time to move to a 64 bit platform.
