### ISSUE TITLE
pywinpty fails to install with pip on a fresh W10 Python installation

### ISSUE THREAD

**Issue by marcoxa** [andfoy/pywinpty#132]
Hi

here is the error trace.  There is a problem creating/overwriting a temp folder for Cython.

I am not much of a Python programmer, and I usually do not want to resort to hairy workarounds.

Do you guys have any idea about how to fix this?

```
PS C:\Users\marco\source\repos> pip install pywinpty
Collecting pywinpty
  Using cached pywinpty-0.5.7.tar.gz (49 kB)
Building wheels for collected packages: pywinpty
  Building wheel for pywinpty (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\marco\appdata\local\programs\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\marco\\AppData\\Local\\Temp\\pip-install-oknsisdc\\pywinpty\\setup.py'"'"'; __file__='"'"'C:\\Users\\marco\\AppData\\Local\\Temp\\pip-install-oknsisdc\\pywinpty\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\marco\AppData\Local\Temp\pip-wheel-av7t9opy'
       cwd: C:\Users\marco\AppData\Local\Temp\pip-install-oknsisdc\pywinpty\
  Complete output (27 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\marco\AppData\Local\Temp\pip-install-oknsisdc\pywinpty\setup.py", line 68, in <module>
      setup(
    File "c:\users\marco\appdata\local\programs\python\python38\lib\site-packages\setuptools\__init__.py", line 152, in setup
      _install_setup_requires(attrs)
    File "c:\users\marco\appdata\local\programs\python\python38\lib\site-packages\setuptools\__init__.py", line 147, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "c:\users\marco\appdata\local\programs\python\python38\lib\site-packages\setuptools\dist.py", line 673, in fetch_build_eggs
      resolved_dists = pkg_resources.working_set.resolve(
    File "c:\users\marco\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 764, in resolve
      dist = best[req.key] = env.best_match(
    File "c:\users\marco\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 1049, in best_match
      return self.obtain(req, installer)
    File "c:\users\marco\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 1061, in obtain
      return installer(requirement)
    File "c:\users\marco\appdata\local\programs\python\python38\lib\site-packages\setuptools\dist.py", line 732, in fetch_build_egg
      return fetch_build_egg(self, req)
    File "c:\users\marco\appdata\local\programs\python\python38\lib\site-packages\setuptools\installer.py", line 131, in fetch_build_egg
      wheel.install_as_egg(dist_location)
    File "c:\users\marco\appdata\local\programs\python\python38\lib\site-packages\setuptools\wheel.py", line 95, in install_as_egg
      self._install_as_egg(destination_eggdir, zf)
    File "c:\users\marco\appdata\local\programs\python\python38\lib\site-packages\setuptools\wheel.py", line 103, in _install_as_egg
      self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
    File "c:\users\marco\appdata\local\programs\python\python38\lib\site-packages\setuptools\wheel.py", line 124, in _convert_metadata
      os.mkdir(destination_eggdir)
  FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\marco\\AppData\\Local\\Temp\\pip-install-oknsisdc\\pywinpty\\.eggs\\Cython-0.29.21-py3.8-win32.egg'
  ----------------------------------------
  ERROR: Failed building wheel for pywinpty
```

**Comment by marcoxa** [comment]
FYI

PS C:\Users\marco\Source\Repos> pip --version
pip 20.2.3 from c:\users\marco\appdata\local\programs\python\python38\lib\site-packages\pip (python 3.8)
PS C:\Users\marco\Source\Repos> python --version
Python 3.8.6

**Comment by ccordoba12** [comment]
We don't provide wheels for 32 bit Python 3.8 installations, sorry. Is your system 32 bit?

**Comment by marcoxa** [comment]
No it isn't.  It is a clean 64 bit installation.  It does not work on my machine(s) :)  Two of them.  I can try a third one.

The problem is the attempted overwriting on a file.

I issue

      pip install jupyter

from scratch, so I doubt it could be some versioning issue of some of the other tool.

Any ideas?

Marco

**Comment by ccordoba12** [comment]
> No it isn't. It is a clean 64 bit installation.

Then you installed a 32 bit Python. Please uninstall it and reinstall a 64 bit version.

> The problem is the attempted overwriting on a file.

No, it's not. pip is trying to build a wheel for you because it can't find a prebuilt one in PyPI. So if your Windows system is 64 bit, simply using a 64 bit Python should fix the problem.

**Comment by marcoxa** [comment]
> 
> > No it isn't. It is a clean 64 bit installation.
> 
> Then you installed a 32 bit Python. Please uninstall it and reinstall a 64 bit version.
> 

Nope.  I installed the 64 bit Python straight from python.org.

> > The problem is the attempted overwriting on a file.
> 
> No, it's not. pip is trying to build a wheel for you because it can't find a prebuilt one in PyPI. So if your Windows system is 64 bit, simply using a 64 bit Python should fix the problem.

I *am using a 64* bit Python as well as everything else.  This is not the problem another user reported some time ago; I did my homework before posting the bug report.  The error is different.  Check the log I posted.

All the best

Marco

**Comment by ccordoba12** [comment]
This is the part in your logs that clearly indicates pip is trying to build the package instead of downloading the wheel:

> Collecting pywinpty
  Using cached pywinpty-0.5.7.tar.gz (49 kB)
Building wheels for collected packages: pywinpty
  Building wheel for pywinpty (setup.py) ... error

As you can see, pip is not pulling our wheel from PyPI but our tarball to build it. And we provide wheels for Python 3.8:

https://pypi.org/project/pywinpty/#files

So forgive me for assuming you have a 32 bit Python. If that's not the case, I really don't understand why pip is not using our wheel, sorry.

**Comment by marcoxa** [comment]
Ok.  That explains the rebuilding vs the downloading.

But I should be able to build the wheel locally no matter what.  I am no expert, but this seem to point to a problem in the building procedure.

All the best

Marco

**Comment by marcoxa** [comment]
Just checking...

So, it is a problem in setup.py after all, isn't it?

**Comment by ccordoba12** [comment]
No, it isn't because we use `setup.py` to build our wheel.

**Comment by marcoxa** [comment]
Ok.  But shouldn't it still be able to build locally from the tar file?

Note that the error is a write error on the file system.

**Comment by ccordoba12** [comment]
> Ok. But shouldn't it still be able to build locally from the tar file?

No, because this is not a pure Python package. It compiles bindings for the Winpty C library using the MinGW toolchain.

> Note that the error is a write error on the file system.

I saw that but have no idea why that happens.

**Comment by marcoxa** [comment]
> 
> 
> > Ok. But shouldn't it still be able to build locally from the tar file?
> 
> No, because this is not a pure Python package. It compiles bindings for the Winpty C library using the MinGW toolchain.
> 

I have the MinGW toolchain installed.  I can also try with the MS Toolchain.

> > Note that the error is a write error on the file system.
> 
> I saw that but have no idea why that happens.

Ok.  So, are there any chances of seeing this assigned to anybody?

**Comment by ccordoba12** [comment]
Sorry, we don't have time to look into this.

**Comment by marcoxa** [comment]
Fair enough... 

In any case, here is the log of the error.  I believe it will tell you why pip cannot find the proper wheel.

I am running this in with the following pip configuration.

```
PS C:\Users\marco\source\repos> pip list
Package    Version
---------- -------
pip        20.2.3
setuptools 50.3.0
wheel      0.35.1

PS C:\Users\marco\source\repos> pip -V
pip 20.2.3 from c:\users\marco\appdata\local\programs\python\python38\lib\site-packages\pip (python 3.8)
```

I don't know exactly what it's happening, but if you look at the lines before pip gives loading the wheel and tries to start building form the tar it looks like there is some mismatch with the wheel's tags.

Marco

[pywinpty.log](https://github.com/spyder-ide/pywinpty/files/5322970/pywinpty.log)

**Comment by marcoxa** [comment]
Hi,

just checking...  my diagnosis is that you guys need to provide a new wheel for pip to find with the combination of pip/setuptools/wheel above (which is "state of the art").

All the best

Marco

**Comment by ccordoba12** [comment]
> my diagnosis is that you guys need to provide a new wheel for pip

Sorry but we're not going to do that. Since this is a core dependency of Jupyter, if the problem you're having would be seen by the rest of its users, we'd have hordes of people complaining about it here.

But you're the only one doing it. So I don't know what happens in your case.

**Comment by marcoxa** [comment]
It may be so.

But maybe you are not seeing it yet, because it looks like most people are using anaconda to install Jupyter.  And anaconda, I discovered, has not upgraded to pip 20.x yet.  Note that I am installing on a very, very fresh Windows and (bare) Python setup.

I may be wrong, but you will be seeing more of this error here, unless a more coordinated upgrade to anaconda and the Jupyter core dependencies will happen in such a way not to expose this bug.

All the best

Marco

**Comment by lefi7z** [comment]
Just for the record, I'm having the exact same problem:


```
>> pip install --no-cache-dir --only-binary :all: pywinpty

ERROR: Could not find a version that satisfies the requirement pywinpty
ERROR: No matching distribution found for pywinpty

>> pip --version
pip 21.0.1

>> python -VV
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]

```

**Comment by andfoy** [comment]
Closing this one, since the errors were reported on the 0.5.x series of pywinpty
