### ISSUE TITLE
Will it provide Python 3.9 version support?

### ISSUE THREAD

**Issue by pasteman** [andfoy/pywinpty#134]

**Comment by bashtage** [comment]
Could use a Python 3.9 wheel for Windows.  Can't currently build.

**Comment by hb20007** [comment]
Facing an error running `pip install pywinpty` with Python 3.9.0. It would be nice to have support.

**Comment by aaronsmith1234** [comment]
I agree, this would be a fantastic thing to have

**Comment by andfoy** [comment]
Thanks for raising this issue, right now the Spyder IDE team was busy with releasing Spyder 5.0.0, however, an update for this package is going to come soon
