### ISSUE TITLE
Can't compile pywinpty on Nvidia TX2

### ISSUE THREAD

**Issue by lee-shun** [andfoy/pywinpty#135]
winpty/cywinpty.c:628:21: fatal error: Windows.h: No such file or directory
  compilation terminated.
  error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pywinpty

but I can build it on the X86 platform well, could you help me? It seems like there's no Window.h on TX2(arm platform)

**Comment by andfoy** [comment]
Hi @lee-shun, it seems that you are trying to compile pywinpty on a Linux machine, while pywinpty is a Windows-only library
