### ISSUE TITLE
Pip attempts to install pywinpty on Python 2.7

### ISSUE THREAD

**Issue by andy-maier** [andfoy/pywinpty#143]
Pywinpty does not declare which Python versions it supports. This causes pip to install the latest version 1.0.0 on Python 2.7 (which fails when installing the 'maturin' dependent package).

The proper fix for this is to declare the supported Python versions in the pywinpty package such that pip recognizes them.

**Comment by ccordoba12** [comment]
Hey @andy-maier, thanks for reporting. You're totally right.

@andfoy, I think we need to add `python_requires` to our `pyproject.toml` to fix this.
