### ISSUE TITLE
pywinpty 1.0.1 doesn't play well with github action

### ISSUE THREAD

**Issue by randy3k** [andfoy/pywinpty#146]
It seems that pywinpty 1.0.1 will freeze the python script running in [github action](https://github.com/randy3k/pywinpty-reproducible-example/runs/2473502796?check_suite_focus=true)

The same script is running fine with [pywinpty 0.5.7](https://github.com/randy3k/pywinpty-reproducible-example/runs/2473502869?check_suite_focus=true).

A reproducible (yet not minimal) example can be found at https://github.com/randy3k/pywinpty-reproducible-example
Also not sure if it is a github action specific thing as I don't have a windows machine to test it.

**Comment by andfoy** [comment]
Hi @randy3k, this is most probably some block related to a read operation in ``PtyProcess``, could you please try to add some print information to see where does the process hangs? You can also jump in into the Github Action machine via RDP by following this repo: https://github.com/nelsonjchen/reverse-rdp-windows-github-actions, please let me know if you are able to find something

**Comment by andfoy** [comment]
@randy3k could you please try with the latest release of pywinpty, v1.1.0?

**Comment by randy3k** [comment]
Yeah, it is working now.
