### ISSUE TITLE
The `backend` argument to `PtyProcess.spawn()` is ignored

### ISSUE THREAD

**Issue by abingham** [andfoy/pywinpty#184]
It appears that the `backend` argument to `PtyProcess.spawn()` is ignored. On [ptyprocess.py:93](https://github.com/spyder-ide/pywinpty/blob/e898abae3f534673982397b3141745a82b885afd/winpty/ptyprocess.py#L93), the `backend` variable is overwritten with the value of the `PYWINPTY_BACKEND` environment variable. Is the intent that the `backend` argument should be used unless the environment variable is set?

First reported in #183.

**Comment by andfoy** [comment]
Thanks for reporting this issue! I'm glad to inform you that it was fixed on v2.0.0
