### ISSUE TITLE
ConPTY is not fully working in CI

### ISSUE THREAD

**Issue by blink1073** [andfoy/pywinpty#217]
Re-running a previously passing [job](https://github.com/spyder-ide/pywinpty/actions/runs/1791280473) shows that ConPTY started timing out on certain tests.  We skipped those tests with XFAIL in #213

**Comment by andfoy** [comment]
This roots out on https://github.com/andfoy/winpty-rs/issues/23

**Comment by andfoy** [comment]
First note: New CI images use Windows Server 2022, whereas previously they used 2019 and some tests are now running as expected

**Comment by andfoy** [comment]
Yes, indeed, now tests are passing: https://github.com/andfoy/winpty-rs/pull/24. I'll produce a `winpty-rs` release and make some changes here

**Comment by blink1073** [comment]
Nice detective work!  Once there is a new `pywinpty` release I'll try removing the explicit backend in `terminado`.
