### ISSUE TITLE
How do I get the same functionality as pty.spawn?

### ISSUE THREAD

**Issue by scastria** [andfoy/pywinpty#330]
Using pythons pty module, I can call spawn with a command and that is it.  It launches the command and gives me an interactive session for that command just as if I ran the command in a real shell.  I don't have to readlines or write lines or anything.  The pty.spawn will just wait for the command to be completed and then control returns back to python.  Is it possible to get that behavior with this library on Windows?

**Comment by andfoy** [comment]
Hi @scastria, the purpose of pywinpty is to spawn a pseudoterminal whose I/O streams are hidden, which given your description makes it sound like the library it is not working for you, could you please provide a GIF and also a script snippet that describes the behaviour you are seeing?

**Comment by scastria** [comment]
I’m not sure I can add any more than what I already posted. With the pty library on Linux, I can call pty.spawn and it will behave just like I ran that command in a real Linux shell. I believe if I call the spawn here in this library, the spawn call will immediately return control to the Python program and exit. I believe this library requires me to go into an infinite loop asking if the process is still alive, etc.

**Comment by andfoy** [comment]
Sorry, I think I didn't understand you completely. So, just to be on the same page, you want to spawn an interactive session on top of your current terminal session and interact with it? If that's the case, then this library doesn't make much sense to you, `pywinpty` is intended to spawn and communicate with pseudoterminals that are detached from a calling console.

I would suggest you to just call your application using `subprocess.Popen` instead as it will inherit the same IO handles as the parent console, thus causing your program to "appear" interactively on top of your current session.

I'll close this issue, feel free to open it again if you have further questions!

**Comment by scastria** [comment]
Just so I am clear, I started off by writing this code:

```
import pty
import shlex

command = shlex.split("docker run -it --rm ubuntu bash")
pty.spawn(command)
```

and it worked beautifully on my Mac.  The above python script worked just as if had run the docker command directly.  I essentially get an interactive shell where I can type commands and get their output.  However, the above python script does not work on Windows as I get the "ModuleNotFoundError: No module named 'termios'" error.

I then search the Internet and pywinpty comes up as a solution for windows.  So then I write this code:

```
from winpty import PtyProcess

PtyProcess.spawn("docker run -it --rm ubuntu bash")
```

I don't get the same behavior.  It seems I need to do more work like reading from stdin and relaying it to the PtyProcess, read from PtyProcess and relay to stdout, and do this in an infinite loop to prevent the python script from exiting until the PtyProcess has exited.

If this is correct, could someone help me with that?  I don't see any docs on this library.

**Comment by andfoy** [comment]
@scastria, thanks for describing your use case. Regarding pywinpty, it is intended to use as a "behind the scenes" pseudoterminal spawner in windows, which are used to spawn programs inside a terminal and then relay the input and output to another application or library that requires it. That's why it requires a fine control over the output and input, as well as the lifecycle of the process that is being run.

Given that you want to interact with the spawned process inside your current terminal session, it is best to use `subprocess.run`, which allows you to spawn a process and communicate with it. You can use it as follows:

```python
import subprocess

subprocess.run(['docker', 'run', -'it', '--rm', 'ubuntu', 'bash'])
```

**Comment by scastria** [comment]
Thank you!!  I could swear I tried all combinations of the subprocess module and nothing worked.  But sure enough, when I try subprocess.run now, it works on both Mac and Windows.  On Windows Command Prompt, it works without any extra work.  But when installing GIT on Windows, you also get the GIT bash terminal.  When using the GIT bash terminal on Windows, it doesn't work out of the box.  I have to prefix the command with winpty and then it works in GIT bash too.

I knew about winpty and tried it as well before, but now it seems to be working.

Thanks for helping me with this.
