### ISSUE TITLE
Provide wheels for python 3.13

### ISSUE THREAD

**Issue by posecl** [andfoy/pywinpty#451]
I tried installing jupyter using python 3.13, which was [released](https://docs.python.org/3/whatsnew/3.13.html) on Oct 7. Currently, the installation fails if the build dependencies for pywinpty aren't installed locally, as the latest wheels for pywinpty on [pypi.org](https://pypi.org/project/pywinpty/#files) only support python up to 3.12.

**Comment by tomlin7** [comment]
@posecl how were you able to solve the issue temporarily in your local machine? I've cargo, rust and maturin installed already + `winpty` binaries, lib in path.

**Comment by posecl** [comment]
I followed the instructions in the [ReadMe](https://github.com/andfoy/pywinpty/blob/main/README.md): I executed rustup‑init.exe from https://rustup.rs/ and installed everything that came with the suggested default setup. After that, I simply re-ran the pip install notebook command, and the wheel for pywinpty was built and installed in the background.

**Comment by bluss** [comment]
Is it possible for this package to [build abi3-py39 wheels](https://pyo3.rs/v0.22.0/features.html#abi3) using maturin/pyo3? Then there could be only one wheel that supports the whole python version range
