### ISSUE TITLE
Include pypiwin32 dependency using an env variable

### ISSUE THREAD

**Issue by andfoy** [andfoy/pywinpty#47]

**Comment by stonebig** [comment]
hi. I'm trouble:
- until now, I'm using http://www.lfd.uci.edu/~gohlke/pythonlibs/#pywin32 wheels (pywin32‑221‑cp35‑cp35m‑win_amd64.whl)
- here you point to pypiwin (pypiwin32-219-cp35-none-win_amd64.whl).

Is it the same thing ?

**Comment by stonebig** [comment]
A suggested  workaround is to postpone the requirement untile cgohlke, pf_moore and other do align.

I really prefer to keep cgohlke wheel on this package.

 https://github.com/spyder-ide/pywinpty/blob/master/setup.py#L42
