### ISSUE TITLE
Release 0.2

### ISSUE THREAD

**Issue by andfoy** [andfoy/pywinpty#54]

**Comment by ccordoba12** [comment]
Why 0.2.0 is not uploaded to PyPi?

**Comment by andfoy** [comment]
I will upload the wheels right now, it was too late yesterday :-)

**Comment by ccordoba12** [comment]
Ok, no problem :-) But please don't make half-way releases for next time.

**Comment by andfoy** [comment]
@ccordoba12 They're available right now on PyPi
