### ISSUE TITLE
Release 0.3.0

### ISSUE THREAD

**Issue by andfoy** [andfoy/pywinpty#64]

**Comment by blink1073** [comment]
I use these bash scripts to help with python and conda-forge releases.  I put all of my feedstock repos in `~/workspace` (the hard coded part).

```bash
function py-release {
    local version=`python setup.py --version 2>/dev/null`
    git commit -a -m "Release $version"
    git tag v$version; true;
    git push origin --all 
    git push origin --tags
    rm -rf dist
    python setup.py sdist
    python setup.py bdist_wheel --universal
    twine upload dist/*
}

function conda-release {
    shasum -a 256 dist/*.tar.gz | awk '{printf $1;}' | pbcopy
    local name=`python setup.py --name 2>/dev/null`
    local version=`python setup.py --version 2>/dev/null`
    open https://github.com/conda-forge/$name-feedstock
    cd ~/workspace/$name-feedstock
    git fetch upstream master
    git checkout -b "release-$version" upstream/master
    subl recipe/meta.yaml
}
```

**Comment by blink1073** [comment]
(Of course, this one is a different beast with the C extension).

**Comment by andfoy** [comment]
@blink1073 Thanks for sharing these scripts, they are handy to avoid some of the manual manoeuvres

**Comment by andfoy** [comment]
> (Of course, this one is a different beast with the C extension).

Yes! It involves MSVC compilation on some VMs

**Comment by blink1073** [comment]
Hmm, there is the approach of using appveyor to publish the wheel if the commit is tagged:

https://refi64.com/posts/using-appveyor-to-distribute-python-wheels.html
https://github.com/project-rig/rig_c_sa/blob/9820d00bee573585695d52df8ee0565b331e6da9/appveyor.yml#L72

**Comment by blink1073** [comment]
Would reduce the friction of whether to make a change because it is difficult to release.

**Comment by andfoy** [comment]
@blink1073 Actually, I would like to automate the publishing process, but I don't have the permissions to add env variables to AppVeyor (To add my username and password). @goanpeca @ccordoba12 what do you think about this ?

**Comment by ccordoba12** [comment]
Sounds good, let me see what I can do about it.

**Comment by ccordoba12** [comment]
@andfoy, you have permissions now to admin all our AppVeyor repos.
