### ISSUE TITLE
Python 2.7 Support?

### ISSUE THREAD

**Issue by blink1073** [andfoy/pywinpty#75]
Given @SylvainCorlay's comment [here](https://github.com/conda-forge/conda-forge.github.io/issues/460#issuecomment-343332639), I think we should resurrect https://github.com/spyder-ide/pywinpty/pull/66.  We are relying on `winpty` to handle the memory alloc/dealloc, and we are not passing OS primitives as described by @mingwandroid [here](https://github.com/conda-forge/conda-forge.github.io/issues/460#issuecomment-343320717).

**Comment by ccordoba12** [comment]
Ok, as long as you fix our conda packages and wheels to use MSVC 14 for Python 2, I'm fine with it.

**Comment by andfoy** [comment]
@blink1073 Ok Steven, go ahead!

**Comment by blink1073** [comment]
Attempt in progress: https://github.com/conda-forge/pywinpty-feedstock/pull/7
