### ISSUE TITLE
Why is the tarball so huge?

### ISSUE THREAD

**Issue by blink1073** [andfoy/pywinpty#77]
Shouldn't the tarball only include source files?  We currently include built files and it is 48MB.

**Comment by blink1073** [comment]
cf https://github.com/spyder-ide/pywinpty/blob/2a6c299c9578d5256f8313c9cfa57c6dcdeef11e/MANIFEST.in#L4-L5

**Comment by andfoy** [comment]
@blink1073 It seems that the Miniconda distribution is being packed alongside the sdist

**Comment by blink1073** [comment]
Ha, I was just about to post that ;).

**Comment by andfoy** [comment]
Maybe we should only add the winpty-specific binaries, I did put the wildcard just because of laziness haha

**Comment by blink1073** [comment]
I don't think any binaries should go in a tarball, you are meant to build those yourself.

**Comment by andfoy** [comment]
> I don't think any binaries should go in a tarball, you are meant to build those yourself.

How do is exclude done only on sdist distributions?

**Comment by blink1073** [comment]
You leave out `include_package_data` and don't put it in the `MANIFEST.in`.

**Comment by blink1073** [comment]
PR coming

**Comment by andfoy** [comment]
> PR coming

Thanks!
